//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioEscolar.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventarioEscolar.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, the asset code must be a positive number..
        /// </summary>
        public static string ASSET_CODE_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("ASSET_CODE_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSET NOT FOUND.
        /// </summary>
        public static string ASSET_NOT_FOUND {
            get {
                return ResourceManager.GetString("ASSET_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conservation status of the asset is not recognized.
        /// </summary>
        public static string CONSERVATION_STATE_NOT_SUPPORTED_ {
            get {
                return ResourceManager.GetString("CONSERVATION_STATE_NOT_SUPPORTED;", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category is mandatory and must be valid..
        /// </summary>
        public static string INVALID_CATEGORY {
            get {
                return ResourceManager.GetString("INVALID_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name. The name must be between 3 and 100 characters..
        /// </summary>
        public static string INVALID_NUMBER_NAME {
            get {
                return ResourceManager.GetString("INVALID_NUMBER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location room must be valid..
        /// </summary>
        public static string INVALID_ROOM_LOCALIZATION {
            get {
                return ResourceManager.GetString("INVALID_ROOM_LOCALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid description. The description can have a maximum of 200 characters..
        /// </summary>
        public static string MAXIMUM_DESCRIPTION_NUMBER {
            get {
                return ResourceManager.GetString("MAXIMUM_DESCRIPTION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid serie number. The serie number can have a maximum of 30 characters..
        /// </summary>
        public static string MAXIMUM_SERIE_NUMBER {
            get {
                return ResourceManager.GetString("MAXIMUM_SERIE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value must be a positive number
        ///ve number.
        /// </summary>
        public static string NEGATIVE_NUMBER {
            get {
                return ResourceManager.GetString("NEGATIVE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
